### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by jorgegomzar** [Hopson97/Balic#3]
Hello again and sorry for the second issue,
Using cmake . , it returns the following error: 
> CMake Error at CMakeLists.txt:16 (add_executable):
  CXX_STANDARD is set to invalid value '17'

This same error appeared to me in your Pixelator repository but fixed it changing that value manually to 11 since the Ubuntu compiler reported me that, loved that one btw! So, after doing the same thing I try to compile with make but returns this:
![screenshot](https://user-images.githubusercontent.com/34076979/46909958-781d3400-cf3b-11e8-8458-7c4925eb08c0.png)
Surely changing the standard to 11 has to be related with the problem, but I still don't know what else to do to finally compile the project.

Thanks for your time.

**Comment by Hopson97** [comment]
This requires C++17 to build. only thing I can think of is you need a newer version of CMake
